services:
  app-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot_agent_base
    restart: "no"
    command: sleep infinity

  backend:
    image: chatbot_agent_base
    restart: always
    depends_on:
      - postgres
    env_file: .env
    working_dir: /app
    command: uvicorn src.backend.main:app --host 0.0.0.0 --port 3434
    ports:
      - "3434:3434"

  ui:
    image: chatbot_agent_base
    restart: always
    depends_on:
      - backend
    env_file: .env
    working_dir: /app
    command: streamlit run src/streamlit_ui/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8086:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - ui

  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    command: >
      bash -c "ollama pull nomic-embed-text && sleep infinity"

volumes:
  postgres_data:
  ollama_data:
