services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "3434:3434"

  ui:
    build:
      context: .
      dockerfile: src/streamlit_ui/Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - backend
    ports:
      - "8501:8501"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8086:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - ui

  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    command: >
      bash -c "ollama pull nomic-embed-text && sleep infinity"

volumes:
  postgres_data:
  ollama_data:
