services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot_agent_base
    command: poetry run uvicorn src.backend.main:app --host 0.0.0.0 --port 3434
    ports:
      - "3434:3434"
    env_file: .env
    volumes:
      - ./src:/app/src
    working_dir: /app
    depends_on:
      - postgres
    restart: always

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot_agent_base
    command: poetry run streamlit run src/streamlit_ui/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    env_file: .env
    volumes:
      - ./src:/app/src
    working_dir: /app
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8086:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - ui

volumes:
  postgres_data:
