---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	process_user_query(process_user_query)
	retrieve_documents(retrieve_documents)
	rewrite_question(rewrite_question)
	generate_answer(generate_answer)
	__end__([<p>__end__</p>]):::last
	__start__ --> process_user_query;
	process_user_query --> retrieve_documents;
	retrieve_documents -.-> generate_answer;
	retrieve_documents -.-> rewrite_question;
	rewrite_question --> process_user_query;
	generate_answer --> __end__;
	retrieve_documents -.-> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
